#!/bin/bash

SCRIPT_DIR=$(cd $(dirname "$0"); pwd)

if [ -z "$UFORA_MANAGER_ADDRESS" ]; then
    echo "Launching Ufora manager"
    $SCRIPT_DIR/start
    MANAGER_STARTED=1
fi

if [ -n "$UFORA_MANAGER_ADDRESS" -o -z "$UFORA_NO_WORKER" ]; then
    echo "Launching Ufora worker"
    $SCRIPT_DIR/ufora-worker start
    WORKER_STARTED=1
fi

function stop_all {
    echo "stop_all"
    if [ -n $WORKER_STARTED ]; then
        echo "Stopping Ufora worker..."
        $SCRIPT_DIR/ufora-worker stop
        echo "Ufora worker stopped."
    fi

    if [ -n $MANAGER_STARTED ]; then
        echo "Stopping Ufora manager..."
        $SCRIPT_DIR/stop
        echo "Ufora manager stopped."
    fi
    exit 0
}

mkfifo /tmp/fifo
trap stop_all SIGTERM SIGINT EXIT
read < /tmp/fifo &
wait
