#!/usr/bin/env bash

#   Copyright 2015 Ufora Inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

UFORA_PACKAGE_ROOT=<UFORA_PACKAGE_ROOT>
UFORA_SCRIPTS_DIR=$UFORA_PACKAGE_ROOT/ufora/scripts

if [[ ! $PYTHONPATH =~ ufora/scripts ]]; then
  export PYTHONPATH=$PYTHONPATH:$UFORA_PACKAGE_ROOT
fi
if [[ ! $PATH =~ $UFORA_PACKAGE_ROOT ]]; then
  export PATH=$PATH:$UFORA_SCRIPTS_DIR
fi
if [[ ! $LD_PRELOAD =~ libtcmalloc ]]; then
  TCMALLOC_PATH=
  for p in /usr/local/lib /usr/lib; do
    if [ -f $p/libtcmalloc.so ]; then
      TCMALLOC_PATH=$p
      break
    fi
  done
  if [ -z $TCMALLOC_PATH ]; then
    echo "ERROR: Can't find required library libtcmalloc.so"
    exit 2
  else
    export LD_LIBRARY_PATH="$TCMALLOC_PATH:$LD_LIBRARY_PATH"
    export LD_PRELOAD="$LD_PRELOAD libtcmalloc.so"
  fi
fi


if [ -z $1 -o $1 == start ]; then
  COMMAND="$UFORA_SCRIPTS_DIR/start_simulation.sh"
  cd $UFORA_PACKAGE_ROOT
  which scl > /dev/null
  if [[ $? -eq 0 ]]; then
    scl -l | grep python27 > /dev/null
    if [[ $? -eq 0 ]]; then
      echo $COMMAND | scl enable python27 -
      exit
    fi
  fi
  $COMMAND
elif [ $1 == stop ]; then
  forever stopall
  killexp FakeEC2Machine
  killexp simulate_cluster
  killexp runEc2Simulator
else
  echo "Unexpected command: $1. Available commands are: start | stop"
fi
