#!/bin/bash

SCRIPT_DIR=$(cd $(dirname "$0"); pwd)

for service in ufora-store ufora-cluster ufora-backend ufora-web; do
    if [ -f $SCRIPT_DIR/$service ]; then
        $SCRIPT_DIR/$service start
        RETVAL=$?
        if [ $RETVAL -ne 0 ]; then
            echo "ERROR: Failed to start $service"
            exit $RETVAL
        fi
    fi
done
