#!/bin/bash

#   Copyright 2015 Ufora Inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

SCRIPT_DIR=$(cd $(dirname "$0"); pwd)

for service in ufora-web ufora-gateway ufora-store; do
    if [ -f $SCRIPT_DIR/$service ]; then
        $SCRIPT_DIR/$service stop
        RETVAL=$?
        if [ $RETVAL -ne 0 ]; then
            echo "ERROR: Failed to stop $service"
        fi
    fi
done
