#!/bin/bash

SCRIPT_DIR=$(cd $(dirname "$0"); pwd)

for service in ufora-web ufora-backend ufora-cluster ufora-store; do
    if [ -f $SCRIPT_DIR/$service ]; then
        $SCRIPT_DIR/$service stop
        RETVAL=$?
        if [ $RETVAL -ne 0 ]; then
            echo "ERROR: Failed to stop $service"
        fi
    fi
done
