#!/bin/bash

SCRIPT_DIR=$(cd $(dirname "$0"); pwd)

# Load configuration helper
. $SCRIPT_DIR/_config.sh
load_config

SERVICE_NAME=ufora-store
SERVICE_LAUNCHER="python"
SERVICE_DIR=$SCRIPT_DIR/../../distributed/SharedState
SERVICE_FILE=$SERVICE_DIR/sharedStateMainline.py
SERVICE_ARGS="--logging=info"
FOREVER_ARGS="--killSignal=SIGTERM"

SERVICE_COMMAND=$1
control_service
