#!/bin/bash

CONFIG_FILE=<UFORA_CONFIG_FILE>
. $CONFIG_FILE

if [ ! -d $UFORA_PACKAGE_ROOT ]; then
  echo "ERROR: Cannot find Ufora package at $UFORA_PACKAGE_ROOT".
  exit 1
fi

# Load configuration helper
. $UFORA_PACKAGE_ROOT/ufora/scripts/init/_config.sh
load_config
set_runtime_env

# start new shell
if [[ -z "$*" ]]; then
  /bin/bash
else
  /bin/bash -c "$*"
fi
