#!/bin/bash

CONFIG_FILE=<UFORA_CONFIG_FILE>
. $CONFIG_FILE

if [ ! -d "$UFORA_PACKAGE_ROOT" ]; then
  echo "ERROR: Cannot find Ufora package at $UFORA_PACKAGE_ROOT".
  exit 1
fi

# Load configuration helper
. $UFORA_PACKAGE_ROOT/ufora/scripts/init/_config.sh
load_config

SERVICE_NAME=ufora-store
SERVICE_LAUNCHER="python"
SERVICE_DIR=$UFORA_PACKAGE_ROOT/ufora/distributed/SharedState
SERVICE_FILE=$SERVICE_DIR/sharedStateMainline.py
SERVICE_ARGS="--logging=info"
FOREVER_ARGS="--killSignal=SIGTERM"

SERVICE_COMMAND=$1
control_service
