#!/bin/bash

CONFIG_FILE=<UFORA_CONFIG_FILE>
. $CONFIG_FILE

if [ ! -d $UFORA_PACKAGE_ROOT ]; then
  echo "ERROR: Cannot find Ufora package at $UFORA_PACKAGE_ROOT".
  exit 1
fi

# Load configuration helper
. $UFORA_PACKAGE_ROOT/ufora/scripts/init/_config.sh
load_config

SERVICE_NAME=ufora-cluster
SERVICE_LAUNCHER="python"
SERVICE_DIR=$UFORA_PACKAGE_ROOT/ufora/machine_model/manager
SERVICE_FILE=$SERVICE_DIR/twisted/twistd
SERVICE_ARGS="-n clustermanager --port=$UFORA_CLUSTER_PORT --signingKey=$TOKEN_SIGNING_KEY --startSharedState=True --localCluster=True"

cd $SERVICE_DIR
SERVICE_COMMAND=$1
control_service

