#!/bin/bash

#   Copyright 2015 Ufora Inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

SCRIPT_DIR=$(cd $(dirname "$0"); pwd)

# Load configuration helper
. $SCRIPT_DIR/_config.sh
load_config

SERVICE_NAME=ufora-store
SERVICE_LAUNCHER="python"
SERVICE_DIR=$SCRIPT_DIR/../../distributed/SharedState
SERVICE_FILE=$SERVICE_DIR/sharedStateMainline.py
SERVICE_ARGS="--logging=info"
FOREVER_ARGS="--killSignal=SIGTERM"

SERVICE_COMMAND=$1
control_service
