#!/bin/bash

CONFIG_FILE=<UFORA_CONFIG_FILE>
. $CONFIG_FILE

if [ ! -d $UFORA_PACKAGE_ROOT ]; then
  echo "ERROR: Cannot find Ufora package at $UFORA_PACKAGE_ROOT".
  exit 1
fi

# Load configuration helper
. $UFORA_PACKAGE_ROOT/ufora/scripts/init/_config.sh
load_config

SERVICE_NAME=ufora-web
SERVICE_LAUNCHER="coffee"
SERVICE_DIR=$UFORA_PACKAGE_ROOT/ufora/web/relay
SERVICE_FILE=$SERVICE_DIR/server.coffee
SERVICE_ARGS="--clusteraddress=localhost --clusterport=$UFORA_CLUSTER_PORT --listenport=$UFORA_WEB_HTTP_PORT --secureport=$UFORA_WEB_HTTPS_PORT --sslKey=$UFORA_SSL_DIR/server.key --sslCert=$UFORA_SSL_DIR/server.crt --sslCa=$UFORA_SSL_DIR/ca.crt --localS3Path=$UFORA_LOCAL_S3_DIR --clustertype=dedicated --interfaceKey=tsunami"

if [ $USE_REAL_S3 == 1 ]; then
  SERVICE_ARGS="$SERVICE_ARGS --useRealS3"
fi

if [ ! -z $USER_DATA_BUCKET ]; then
  SERVICE_ARGS="$SERVICE_ARGS --uploadBucket=$USER_DATA_BUCKET"
fi

REDIS_CLI=$UFORA_PACKAGE_BIN_DIR/redis-cli
REDIS_SERVER=$UFORA_PACKAGE_BIN_DIR/redis-server
if [[ `$REDIS_CLI ping 2> /dev/null` != "PONG" ]]; then
    echo "Starting redis server"
    $REDIS_SERVER --dbfilename ufora.rdb --dir $UFORA_REDIS_DIR --save 60 1 > $UFORA_REDIS_DIR/redis.log &
    sleep 1
    if [[ `$REDIS_CLI ping ` != "PONG" ]]; then
        echo "ERROR: cannot start redis server from $REDIS_SERVER"
        exit 2
    fi
fi

SERVICE_COMMAND=$1
control_service
