#!/bin/bash

SCRIPT_DIR=$(cd $(dirname "$0"); pwd)

# Load configuration helper
. $SCRIPT_DIR/_config.sh
load_config

SERVICE_NAME=ufora-web
SERVICE_LAUNCHER="coffee"
SERVICE_DIR=$SCRIPT_DIR/../../web/relay
SERVICE_FILE=$SERVICE_DIR/server.coffee
SERVICE_ARGS="--gatewayport=$UFORA_GATEWAY_PORT --port=$UFORA_WEB_HTTP_PORT"

SERVICE_COMMAND=$1
control_service
