#!/bin/bash

SCRIPT_DIR=$(cd $(dirname "$0"); pwd)

# Load configuration helper
. $SCRIPT_DIR/_config.sh
load_config

SERVICE_NAME=ufora-gateway
SERVICE_LAUNCHER="python"
SERVICE_DIR=$SCRIPT_DIR
SERVICE_FILE=$SERVICE_DIR/ufora-gateway.py
SERVICE_ARGS=""
FOREVER_ARGS="--killSignal=SIGTERM"

SERVICE_COMMAND=$1
control_service
