#!/bin/bash
ps auwx | grep $1 | grep -v grep | grep -v killexp | sed 's/.........\(.....\).*/\1/' | xargs echo "killing PIDs: "
ps auwx | grep $1 | grep -v grep | grep -v killexp | sed 's/.........\(.....\).*/\1/' | xargs -r -n 1 kill -9
